export const FETCH_OPENWEATHER_DATA = 'FETCH_OPENWEATHER_DATA';
export const FETCH_OPENWEATHER_ERROR = 'FETCH_OPENWEATHER_ERROR';

export const FETCH_WUNDERGROUND_DATA = 'FETCH_WUNDERGROUND_DATA';
export const FETCH_WUNDERGROUND_ERROR = 'FETCH_OPENWEATHER_ERROR';

export const FETCH_YELP_TOKEN = "FETCH_YELP_TOKEN";
export const FETCH_YELP_TOKEN_ERROR = "FETCH_YELP_TOKEN_ERROR";
